# Generated by Django 4.1.2 on 2022-10-06 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal_for_month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Goal', models.CharField(max_length=100)),
                ('Month', models.DateTimeField(auto_now=True)),
                ('difficulty', models.FloatField(default='')),
                ('reason_for_goal', models.TextField(default='')),
                ('is_closed', models.BooleanField(default=False)),
                ('is_favorite', models.BooleanField(default=False)),
            ],
        ),
    ]
