# Generated by Django 4.1.2 on 2022-10-09 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0002_goal_for_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal_for_month',
            name='Month',
            field=models.IntegerField(default=True),
        ),
        migrations.AlterField(
            model_name='goal_for_month',
            name='difficulty',
            field=models.TextField(default=''),
        ),
    ]
